### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fedemartinm** [fedemartinm/fast-styles#1]
- [x] Add support for theming
- [x] Add support for design tokens
- [x] Include a set of basic components as a showcase of the library
- [x] Conduct benchmarks with other libraries
- [x] Introduce hooks as an alternative to styled components

**Comment by fedemartinm** [comment]
Libraries for comparison:
https://github.com/joe-bell/cva
https://github.com/oktaysenkan/style-variants
https://github.com/gluestack/gluestack-style
https://github.com/GeekyAnts/nativebase
https://github.com/styled-components
https://github.com/stitchesjs/stitches
https://github.com/tamagui/tamagui

**Comment by fedemartinm** [comment]
- Using a global theme for now seems like an appropriate solution. We will see in the future if automatically mapping the tokens is useful.

- Creating primitives will be addressed in a separate issue.
- No hooks for now.

**Comment by efstathiosntonas** [comment]
hey @fedemartinm, just wanted you to know I've added your lib in the [benchmarks repo](https://github.com/efstathiosntonas/react-native-style-libraries-benchmark), congrats on the scores, great job.

**Comment by fedemartinm** [comment]
@efstathiosntonas that's awesome! Thanks for including this lib. 
Keeping up good performance is a fundamental part of this project. I'll keep a close eye on those benchmarks
